    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen          80;
        listen          [::]:80;

        location / {
            proxy_pass          http://host.docker.internal:9998;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection $connection_upgrade;
            proxy_set_header    Host            $host;
            proxy_set_header    X-Real-IP       $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
